[package]
name = "sourcetrait_lib_note"
version = "0.0.1"
edition = "2024"
description = "A very simple Markdown notes manager"
authors = ["SourceTrait <development@sourcetrait.com>"]
license = "AGPL-3.0-or-later"
repository = "https://github.com/sourcetrait/sourcetrait_lib"
homepage = "https://sourcetrait.com"
categories = []
keywords = ["sourcetrait", "lib", "note", "markdown"]

[dependencies]
chrono.workspace = true
derive_builder.workspace = true
dirs.workspace = true
heck.workspace = true
serde.workspace = true
shellexpand.workspace = true
snafu.workspace = true
strum.workspace = true
toml.workspace = true
sourcetrait_chronox.workspace = true
sourcetrait_tomlx.workspace = true
sourcetrait_stdx.workspace = true

[dev-dependencies]
sourcetrait_testing.workspace = true
