XDG_CONFIG_HOME DEFAULT=@{HOME}/.config
XDG_CACHE_HOME DEFAULT=@{HOME}/.sys/.xdg/cache
XDG_DATA_HOME DEFAULT=@{HOME}/.sys/.xdg/data
XDG_STATE_HOME DEFAULT=@{HOME}/.sys/.xdg/state

XDGX_STRICT_CONFIG_HOME DEFAULT=@{HOME}/.config/strict
XDGX_STRICT_CACHE_HOME DEFAULT=@{HOME}/.sys/.xdg/strict/cache
XDGX_STRICT_DATA_HOME DEFAULT=@{HOME}/.sys/.xdg/strict/data
XDGX_STRICT_STATE_HOME DEFAULT=@{HOME}/.sys/.xdg/strict/state

XDGX_SECURE_CONFIG_HOME DEFAULT=@{HOME}/.config/secure
XDGX_SECURE_CACHE_HOME DEFAULT=@{HOME}/.sys/.xdg/secure/cache
XDGX_SECURE_DATA_HOME DEFAULT=@{HOME}/.sys/.xdg/secure/data
XDGX_SECURE_STATE_HOME DEFAULT=@{HOME}/.sys/.xdg/secure/state

XDGX_EXECUTE_HOME DEFAULT=@{HOME}/.sys/local/bin
XDGX_LIBRARY_HOME DEFAULT=@{HOME}/.sys/local/lib
XDGX_PACKAGE_HOME DEFAULT=@{HOME}/.sys/local/pkg

